### ISSUE TITLE
Acabar el ejercicio

### ISSUE THREAD

**Issue by nasivuela** [Adalab/dorcas-s3-evaluacion-intermedia-ElisabetAS#1]
Te dejo pistas para acabar el ejercicio:

- Cuando iteras sobre el array de pokemons (con el map en App.js), estás pintando el componente 'PokemonList' por cada item del array. Lo ideal sería pintar un componente 'Pokemon' por cada item.

- Recuerda que ninguna prop llega mágicamente a un componente, tenemos que pasarlas nosotras con atributos. Dale caña y pásale props a tus componentes.

- Una vez tengas tu listado podrías: mejorar la estructura de HTML (main, h1...) crear una carpeta `components` para organizar mejor la app, instalar la librería `prop-types` con npm y añadir comprobación de tipos, animarte con el css...

A por ello!

**Comment by ElisabetAS** [comment]
He conseguido pasar las 'props' de un componente a otro para que se pinten... pero no se si me faltan habilidades o es que hay algunos pokémon que no tienen lo tengo que mirar... y bueno aún me queda curro... me ha costado bastante que se pintaran...

No entiendo el error de la 'key' no me quedó claro donde hay que ponerla ni para que sirve ni na...

Si hago una carpeta components y muevo mis cosas de sitio no tengo que cambiar el código no?
Quiero decir no se me romperá todo o sí? D:

**Comment by ElisabetAS** [comment]
Ah, sí que tienen todos sus habilidades, tranquila!!

**Comment by nasivuela** [comment]
Buen trabajo @ElisabetAS !!!

Cuando creamos un listado de elementos, tenemos que añadir un atributo key con un valor único para cada elemento, más info aquí --> https://reactjs.org/docs/lists-and-keys.html

Aprovecho y te paso más cosas que puedes mejorar:

- Añadir carpeta components para que todo esté más organizadito.
- Mejorar la indentación.
- No descuidar la semántica de HTML (main, h1...)
- Instalar la librería prop-types y usarla para comprobar el tipado js de las props.
- Publicar en Github Pages

A por ello!

**Comment by ElisabetAS** [comment]
Ya está!
COn las props no he atinado a ver si con el proyecto las pillo el truqui y durante las vacaciones le meto caña a estos cutre-pokemon...
Funciona en GitHubPages

**Comment by nasivuela** [comment]
Buen trabajo!!!
